[tool.poetry]
name = "reproducer"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
ddtrace = "2.9.1"
flask = "3.0.3"
gunicorn = { version = "22.0.0", extras = ["gevent"] }
mongoengine = "0.28.2"